[UnAuthorizedError]
other = "برای دسترسی به این قسمت باید ابتدا وارد شوید."

[ForbiddenError]
other = "شما اجازه دسترسی به این قسمت را ندارید."

[ValidationError]
other = "اطلاعات ارسالی معتبر نمی‌باشد."

[NotFoundError]
other = "اطلاعات درخواستی یافت نشد."

[InternalError]
other = "متاسفانه سیستم با خطای داخلی مواجه شد. برای تسریع در رفع این مشکل لطفا با پشتیبانی تماس بگیرید."
